pipeline {
    agent any
    stages {
        stage('BUILD') {
            steps {
                echo 'BUILD - Application'
            }
        }
stage('TEST') {
            steps {
                echo 'TEST- Application'
            }
        }
stage('DEPLOY') {
            steps {
                echo 'DEPLOY- Application'
            }
        }
    }
	post {
		always {
			emailext body: 'Sample for executing declarative Jenkins File job', subject: 'JenkinsFile Job', to: 'myselfshrikantkale@gmail.com'
		}
	}
}
